/* This file was generated by syncqt. */
#ifndef QT_QMFCLIENT_VERSION_H
#define QT_QMFCLIENT_VERSION_H

#define QMFCLIENT_VERSION_STR "5.0.0"

#define QMFCLIENT_VERSION 0x050000

#endif // QT_QMFCLIENT_VERSION_H
